### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by zsb87** [phev8/ward-metrics#1]
Your library is really useful and usable!  I would kindly like to ask one question.  Did I use it in a wrong way when I take this as input?

    ground_truth_test = [(1,4),(12,13)]
    detection_test = [(2,3)]

    print(eval_events(ground_truth_test, detection_test))

The error message is:

File "//ward-metrics-master/wardmetrics/core_methods.py", line 456, in _get_standard_event_metrics
    if detected_event_scores[i] == "I'":
IndexError: list index out of range

Thank you!

**Comment by phev8** [comment]
Thank you for the feedback. I'll look into the issue as soon as I can, latest next week.

**Comment by phev8** [comment]
Thank you very much for the feedback. There was indeed a logical error at computing the borders of the first segment if there were no evaluation start and evaluation end given. 
I've fixed it with the latest comment and updated the pip version as well (should have the version 0.9.3).
If you notice any other mistakes, please report them as well.
