### ISSUE TITLE
importing problem

### ISSUE THREAD

**Issue by AffDk** [phev8/ward-metrics#2]
I am trying to import the package but python does not find it after installation.
I use it with windows 10, Anaconda installation. The installation goes through apparently without trouble but anyhow the package is not visible to python. Can it be because it is not compatible with windows or perhaps conda environment?

Best regards

**Comment by phev8** [comment]
Good question. I never tried it with Windows or Anaconda together. Only on linux and mac.
However, I am also not aware why it would not work on Windows. 

How do you try to import? Asking cause now I opened this after a while and by default I was trying to import it with the wrong names...

**Comment by AffDk** [comment]
As instructed like

import wardmetrics

Is this what you mean?

**Comment by phev8** [comment]
Yes. I just tried on Win11 and python3.9, installing simply with `pip install ward-metrics`, worked for me as expected and could import, and use the library. 
Maybe check, if you have different python instances installed on your system (e.g. one with anaconda and one with the python installer), and when using the python command, it picks the one where you have installed the package.

**Comment by AffDk** [comment]
it is then like a mystery to me. I have only the anaconda installation. I have created an environment in conda (here called filternet) to avoid further conflicts. I tried to uninstall and then installl and import it within a jupyter notebook. you can see a snapshot below. I hope it gives you a clue but I cannot spot what the problem may be.
![image](https://user-images.githubusercontent.com/42941133/152321059-cf9617a6-9bea-4a7b-83f3-6c8475a71735.png)

**Comment by phev8** [comment]
It sounds to me this is an issue about the environment. Maybe related to this:

https://stackoverflow.com/questions/61265125/jupyter-notebook-module-not-found-even-after-pip-install

**Comment by AffDk** [comment]
Thanks for the suggestion. I did it and also change the kernel in jupyter notebook to the one installed according the instruction mentioned in the abovementioned webpage and it did the trick. thanks
